"use strict";

// DOM/Plotly presentation for the Time Series workspace.  Numerical calculations are
// delegated to compare-core.js; request construction/fetching live in compare-request.js.

function renderBoardState() {
  if (!$("boardDirtyMark")) return;
  const board = boardById(indicatorState.activeBoardId); const dirty = boardIsDirty();
  $("boardDirtyMark").classList.toggle("is-hidden", !dirty); $("boardUnsavedNote").classList.toggle("is-hidden", !dirty);
  $("updateBoardButton").classList.toggle("is-emphasised", dirty);
  $("boardMenuSummary").title = board ? `当前 board：${board.name}${dirty ? " · 有未保存的修改" : ""}` : "尚未保存为 board";
  $("activeBoardLabel").textContent = board ? `当前 board：${board.name}（保存于 ${board.savedAt.slice(0, 10) || "—"}）${dirty ? " · 有未保存的修改" : ""}` : "当前工作区尚未保存为 board。";
}
function renderBoards() {
  const select = $("boardSelect"); if (!select) return;
  const options = indicatorState.boards.map((board) => `<option value="${board.id}">${escapeHtml(board.name)} · ${board.items.length} indicators</option>`).join("");
  select.innerHTML = `<option value="">选择一个 board…</option>${options}`;
  if (indicatorState.activeBoardId !== null) select.value = String(indicatorState.activeBoardId);
  const active = boardById(indicatorState.activeBoardId); if (active && !$("boardName").value.trim()) $("boardName").value = active.name;
  $("boardCount").textContent = String(indicatorState.boards.length); renderBoardState(); renderBoardActions();
}
function renderBoardActions() {
  $("updateBoardButton").disabled = boardById(indicatorState.activeBoardId) === null;
  $("deleteBoardButton").disabled = boardById($("boardSelect").value) === null;
  $("loadBoardButton").disabled = boardById($("boardSelect").value) === null;
}

function requestSystemFields(draft) { draft.volatilityConvention = "bsVol"; draft.layout = "matrix"; return ""; }
function maturityModeField(draft) {
  const legacyFixed = draft.maturityMode === "fixed" ? '<option value="fixed" selected>Fixed date · legacy</option>' : "";
  return `<label class="field field-wide config-first"><span>Maturity type</span><select data-draft="maturityMode"><option value="sliding" ${draft.maturityMode === "sliding" ? "selected" : ""}>Sliding tenor</option><option value="listed" ${draft.maturityMode === "listed" ? "selected" : ""}>Listed expiry</option>${legacyFixed}</select></label>`;
}
function optionList(values) { return values.map((value) => `<option value="${escapeHtml(value)}"></option>`).join(""); }
function maturityValueField(draft) {
  if (draft.maturityMode === "sliding") {
    const maturities = draft.strikeKind === "delta" ? state.capabilities?.deltaMaturities || [] : state.capabilities?.slidingMaturities || [];
    return `<label class="field field-wide"><span>Sliding maturity</span><input data-draft="slidingMaturity" value="${escapeHtml(draft.slidingMaturity)}" list="indicatorMaturityOptions" autocomplete="off" /><datalist id="indicatorMaturityOptions">${optionList(maturities)}</datalist><small>可键盘输入，但必须是数据源 OpenAPI 列出的 tenor；不支持的值会在本地明确拒绝。</small></label>`;
  }
  if (draft.maturityMode === "fixed") return `<label class="field field-wide"><span>Fixed maturity date · legacy</span><input data-draft="expiry" type="date" value="${escapeHtml(draft.expiry)}" /><small>仅为兼容已有 board / indicator 保留；新建指标不再提供 Fixed date。</small></label>`;
  const code = draft.instrumentCode.trim(); const discovery = indicatorState.discovery; const defaultDate = $("endDate")?.value || isoDate(new Date());
  const observationDate = indicatorState.listedObservationDate || discovery?.date || defaultDate; indicatorState.listedObservationDate = observationDate;
  const matches = discovery && discovery.code === code && discovery.date === observationDate;
  let expiryOptions = '<option value="">Loading listed expiries…</option>'; let disabled = "disabled"; let note = `正在读取 ${observationDate} 的 listed expiries…`;
  if (matches && discovery.status === "ready") {
    const maturities = [...new Set(discovery.snapshot.maturities || [])].sort();
    expiryOptions = `<option value="">Select listed expiry</option>${maturities.map((value) => `<option value="${escapeHtml(value)}" ${draft.expiry === value ? "selected" : ""}>${escapeHtml(value)}</option>`).join("")}`;
    disabled = ""; note = `${observationDate}：${maturities.length} 个 available listed expiries。`;
  } else if (matches && discovery.status === "error") {
    expiryOptions = '<option value="">Listed expiries unavailable</option>';
    const parts = [discovery.errorCode, discovery.message || "unknown error", discovery.suggestedAction ? `建议：${discovery.suggestedAction}` : null, discovery.requestId ? `Request ${discovery.requestId}` : null].filter(Boolean);
    note = parts.map(escapeHtml).join(" · ");
  }
  return `<div class="field-grid two config-grid listed-expiry-direct"><label class="field"><span>Observation date</span><input id="indicatorObservationDate" type="date" value="${escapeHtml(observationDate)}" /></label><label class="field"><span>Listed expiry</span><select id="indicatorListedExpiry" data-draft="expiry" ${disabled}>${expiryOptions}</select></label></div><small id="indicatorListedExpiryStatus">${note}</small>`;
}
function strikeFields(draft) {
  const fixedMaturity = draft.maturityMode !== "sliding";
  const selectedKind = fixedMaturity && draft.strikeKind === "delta" ? "percentage" : !fixedMaturity && draft.strikeKind === "absolute" ? "percentage" : draft.strikeKind;
  draft.strikeKind = selectedKind; let coordinate = "";
  if (selectedKind === "percentage") {
    coordinate = `<div class="field-grid two config-grid"><label class="field"><span>Percentage</span><input data-draft="moneyness" type="number" step="0.1" value="${escapeHtml(draft.moneyness)}" list="indicatorMoneynessOptions" /><datalist id="indicatorMoneynessOptions">${optionList(state.capabilities?.moneynessLevels || [])}</datalist></label><label class="field"><span>Relative to</span><select data-draft="moneynessBasis"><option value="relative_to_forward" ${draft.moneynessBasis === "relative_to_forward" ? "selected" : ""}>Fwd</option><option value="relative_to_spot_ref" ${draft.moneynessBasis === "relative_to_spot_ref" ? "selected" : ""}>Spot</option></select></label></div>`;
  } else if (selectedKind === "delta") {
    coordinate = `<label class="field field-wide"><span>Put / Call delta</span><input data-draft="delta" value="${escapeHtml(draft.delta)}" list="indicatorDeltaOptions" autocomplete="off" /><datalist id="indicatorDeltaOptions">${optionList(state.capabilities?.deltaStrikes || [])}</datalist><small>Delta 只支持 sliding maturity 和数据源官方 delta codes。</small></label>`;
  } else {
    const discovery = indicatorState.discovery; const expiry = draft.expiry; const ready = discovery?.strikeStatus === "ready" && discovery?.strikeExpiry === expiry; const strikes = ready ? discovery.strikes || [] : [];
    let note = "先选择 Listed expiry；随后会自动加载该 expiry 的 available strikes。";
    if (expiry && discovery?.strikeStatus === "loading" && discovery?.strikeExpiry === expiry) note = `正在加载 ${expiry} 的 available strikes…`;
    else if (expiry && discovery?.strikeStatus === "error" && discovery?.strikeExpiry === expiry) note = [discovery.strikeErrorCode, `Strike list 读取失败：${discovery.strikeMessage || "unknown error"}`, discovery.strikeSuggestedAction ? `建议：${discovery.strikeSuggestedAction}` : null, discovery.strikeRequestId ? `Request ${discovery.strikeRequestId}` : null, "仍可手动输入绝对 strike。"].filter(Boolean).map(escapeHtml).join(" · ");
    else if (expiry && ready) note = `${expiry}：${strikes.length} 个 available strikes；可直接输入任意正数，也可从下拉建议选择。`;
    coordinate = `<label class="field field-wide"><span>Absolute strike</span><input data-draft="absoluteStrike" type="number" min="0.000001" step="any" value="${escapeHtml(draft.absoluteStrike)}" list="indicatorAbsoluteStrikeOptions" autocomplete="off" ${expiry ? "" : "disabled"} /><datalist id="indicatorAbsoluteStrikeOptions">${strikes.map((value) => `<option value="${escapeHtml(value)}"></option>`).join("")}</datalist><small id="indicatorAbsoluteStrikeStatus">${note}</small></label>`;
  }
  const combinationNote = fixedMaturity ? "" : "<small>数据源 API 不支持 Sliding maturity + Absolute strike；系统不会自动把 3M 转成邻近 expiry。</small>";
  return `<label class="field field-wide"><span>Strike type</span><select data-draft="strikeKind"><option value="percentage" ${selectedKind === "percentage" ? "selected" : ""}>Percentage moneyness</option><option value="delta" ${selectedKind === "delta" ? "selected" : ""} ${fixedMaturity ? "disabled" : ""}>Put / Call delta</option><option value="absolute" ${selectedKind === "absolute" ? "selected" : ""} ${fixedMaturity ? "" : "disabled"}>Absolute strike</option></select>${combinationNote}</label>${coordinate}`;
}
function listedDiscoveryPanel() { return ""; }
function derivedOperandFields(draft) {
  const candidates = operandCandidates();
  if (!candidates.length) return '<div class="system-default-card"><strong>还没有可用的操作数</strong><span>先添加至少一个已保存 indicator，再用它们组合出新指标。</span></div>';
  const operandOptions = (selected) => candidates.map((item) => `<option value="${item.id}" ${String(item.id) === String(selected) ? "selected" : ""}>${escapeHtml(indicatorLabel(item))}</option>`).join("");
  const operators = Object.entries(OPERATOR_SYMBOLS).map(([key, symbol]) => `<option value="${key}" ${draft.operator === key ? "selected" : ""}>${symbol}</option>`).join("");
  return `<div class="derived-operands"><label class="field"><span>Indicator A</span><select data-draft="operandA">${operandOptions(draft.operandA)}</select></label><label class="field operator-field"><span>Operator</span><select data-draft="operator">${operators}</select></label><label class="field"><span>Indicator B</span><select data-draft="operandB">${operandOptions(draft.operandB)}</select></label></div><p class="derived-preview">${escapeHtml(derivedPreviewLabel(draft))}</p>`;
}
function derivedPreviewLabel(draft) { const left = itemById(draft.operandA); const right = itemById(draft.operandB); return !left || !right ? "请选择两个已保存的 indicator。" : `${indicatorLabel(left)}  ${OPERATOR_SYMBOLS[draft.operator]}  ${indicatorLabel(right)}`; }
function renderIndicatorConfig() {
  const draft = indicatorState.draft; const config = $("indicatorConfig"); if (!config) return; let html = "";
  if (draft.type === "implied_vol") { html = `${requestSystemFields(draft)}${maturityModeField(draft)}${maturityValueField(draft)}${strikeFields(draft)}${listedDiscoveryPanel(draft)}`; $("indicatorBuilderNote").textContent = "IV 使用精确 maturity + strike 坐标。Vol convention 与 layout 都是数据源请求字段；缺失值不会换成邻近坐标。"; }
  else if (draft.type === "realized_vol") { html = `${requestSystemFields(draft)}<div class="field-grid two config-grid"><label class="field"><span>Window · sessions</span><input data-draft="rvWindow" type="number" min="2" step="1" list="rvWindowOptions" value="${escapeHtml(draft.rvWindow)}" /></label><label class="field"><span>Alignment</span><select data-draft="rvAlignment"><option value="trailing" ${draft.rvAlignment === "trailing" ? "selected" : ""}>Trailing</option><option value="forward" ${draft.rvAlignment === "forward" ? "selected" : ""}>Forward</option></select></label></div>`; $("indicatorBuilderNote").textContent = "RV 接受任意 ≥2 的整数窗口，不取最近档位。Spot 来自数据源 IV 响应，因此独立 RV 会明确使用 3M K/F 100% 作为取数载体；该坐标不进入 RV 公式。"; }
  else if (draft.type === "spot") { html = `${requestSystemFields(draft)}<div class="system-default-card"><strong>无需额外参数</strong><span>原始未复权 spot / price-return source</span></div>`; $("indicatorBuilderNote").textContent = "当前 Cortex 数据路径把 spot 放在 IV response 内；系统用 3M K/F 100% 请求承载 spot，并在指标卡中明示。不会把该参考 IV 当作用户选择的指标。"; }
  else if (draft.type === "derived") { ensureDerivedDefaults(draft); html = derivedOperandFields(draft); $("indicatorBuilderNote").textContent = "运算在浏览器内按共同观察日逐日进行，不发送新的取数请求。任一操作数缺失该日期或该日期无有效值时，结果保持为空，不插值、不前向填充；除数为 0 同样保持为空。"; }
  else { html = `${requestSystemFields(draft)}${maturityModeField(draft)}${maturityValueField(draft)}${listedDiscoveryPanel(draft)}`; $("indicatorBuilderNote").textContent = "Forward 按所选 maturity 读取数据源 forward curve；系统用 K/F 100% 作为响应载体。该 moneyness 不改变同一期限的 forward 值。"; }
  config.innerHTML = html; bindDraftFields(); bindIndicatorDiscovery();
}
function bindDraftFields() {
  document.querySelectorAll("#indicatorConfig [data-draft]").forEach((field) => {
    const update = () => { indicatorState.draft[field.dataset.draft] = field.value; if (["maturityMode", "strikeKind"].includes(field.dataset.draft)) { indicatorState.discovery = null; renderIndicatorConfig(); } if (["operandA", "operator", "operandB"].includes(field.dataset.draft)) { const preview = document.querySelector(".derived-preview"); if (preview) preview.textContent = derivedPreviewLabel(indicatorState.draft); } };
    field.addEventListener("change", update); if (field.tagName === "INPUT") field.addEventListener("input", update);
  });
}
function bindIndicatorDiscovery() {
  if (indicatorState.draft.maturityMode !== "listed") return;
  const observation = $("indicatorObservationDate");
  if (observation) {
    const sync = () => { indicatorState.listedObservationDate = observation.value; indicatorState.draft.expiry = ""; indicatorState.draft.absoluteStrike = ""; };
    observation.addEventListener("keydown", (event) => { if (/^[0-9]$/.test(event.key) || ["Backspace", "Delete"].includes(event.key)) indicatorState.listedDateTyping = true; if (event.key === "Enter") { event.preventDefault(); sync(); indicatorState.listedDateTyping = false; if (validIsoDate(observation.value)) loadIndicatorCoordinates(observation.value); } });
    observation.addEventListener("input", sync);
    observation.addEventListener("change", () => { sync(); if (!indicatorState.listedDateTyping && validIsoDate(observation.value)) loadIndicatorCoordinates(observation.value); });
    observation.addEventListener("blur", () => { sync(); const date = observation.value; indicatorState.listedDateTyping = false; if (validIsoDate(date) && (indicatorState.discovery?.code !== indicatorState.draft.instrumentCode.trim() || indicatorState.discovery?.date !== date)) loadIndicatorCoordinates(date); });
  }
  const expirySelect = $("indicatorListedExpiry");
  expirySelect?.addEventListener("change", () => { const expiry = expirySelect.value; if (indicatorState.draft.strikeKind === "absolute") { indicatorState.draft.absoluteStrike = ""; if (expiry) loadListedStrikes(expiry); } });
  const code = indicatorState.draft.instrumentCode.trim(); const date = indicatorState.listedObservationDate || observation?.value || $("endDate")?.value || isoDate(new Date()); indicatorState.listedObservationDate = date;
  const discovery = indicatorState.discovery; const matches = discovery && discovery.code === code && discovery.date === date;
  if (!matches) { queueMicrotask(() => { if (indicatorState.draft.maturityMode === "listed" && indicatorState.draft.instrumentCode.trim() === code && indicatorState.listedObservationDate === date && !indicatorState.listedDateTyping) loadIndicatorCoordinates(date); }); return; }
  if (discovery.status === "ready" && indicatorState.draft.strikeKind === "absolute" && indicatorState.draft.expiry && !(discovery.strikeExpiry === indicatorState.draft.expiry && ["loading", "ready", "error"].includes(discovery.strikeStatus))) {
    const expiry = indicatorState.draft.expiry; queueMicrotask(() => { if (indicatorState.draft.maturityMode === "listed" && indicatorState.listedObservationDate === date && indicatorState.draft.expiry === expiry && !indicatorState.listedDateTyping) loadListedStrikes(expiry); });
  }
}
function renderBuilderMode() {
  const item = indicatorState.editingId === null ? null : itemById(indicatorState.editingId); if (indicatorState.editingId !== null && !item) indicatorState.editingId = null; const editing = item !== null;
  $("addIndicatorButton").querySelector("span").textContent = editing ? "保存修改" : "添加并加载指标"; $("addIndicatorButton").querySelector("strong").textContent = editing ? "✓" : "＋";
  $("cancelEditButton").classList.toggle("is-hidden", !editing); $("builderModeNote").classList.toggle("is-hidden", !editing); $("builderModeNote").textContent = editing ? `正在编辑：${indicatorLabel(item)}` : "";
}

function renderBulkBar() {
  if (!indicatorState.bulkMode) return; const targets = bulkTargetIds(); const pulled = targets.size - indicatorState.bulkSelection.size;
  $("bulkCount").textContent = pulled ? `已选 ${indicatorState.bulkSelection.size} 项（含运算指标带入的 ${pulled} 个操作数，共 ${targets.size} 项）` : `已选 ${targets.size} 项`;
  syncBulkInstrumentButtons(); renderBulkMaturityControls();
}
function handleSavedIndicatorChange(event) {
  const bulkBox = event.target.closest("[data-bulk-select]"); if (bulkBox) return setBulkSelection(Number(bulkBox.dataset.bulkSelect), bulkBox.checked);
  const laneSelect = event.target.closest("[data-indicator-lane]"); if (laneSelect) { const item = itemById(Number(laneSelect.dataset.indicatorLane)); if (!item) return; item.config.chartLane = laneSelect.value; persistWorkspace(); refreshWorkspacePanels({ details: false }); return; }
  const toggle = event.target.closest("[data-indicator-toggle]"); if (!toggle) return; const item = itemById(Number(toggle.dataset.indicatorToggle)); if (!item) return; item.active = toggle.checked; persistWorkspace(); refreshWorkspacePanels({ details: false }); fetchMissingDependencies();
}
function handleSavedIndicatorClick(event) {
  const detail = event.target.closest("[data-indicator-detail]"); if (detail) { indicatorState.selectedDetailId = Number(detail.dataset.indicatorDetail); persistWorkspace(); renderIndicatorDetails(); $("resultWorkspace").scrollIntoView({ behavior: "smooth", block: "start" }); return; }
  const edit = event.target.closest("[data-indicator-edit]"); if (edit) return startEditing(Number(edit.dataset.indicatorEdit));
  const duplicate = event.target.closest("[data-indicator-duplicate]"); if (duplicate) return duplicateIndicator(Number(duplicate.dataset.indicatorDuplicate));
  const del = event.target.closest("[data-indicator-delete]"); if (!del) return; const id = Number(del.dataset.indicatorDelete);
  const dependents = indicatorState.items.filter((item) => item.type === "derived" && [item.config.operandA, item.config.operandB].some((operand) => String(operand) === String(id)));
  if (dependents.length) return showIndicatorFormError(`该 indicator 被 ${dependents.length} 个运算指标引用（${dependents.map(indicatorLabel).join("；")}），请先删除这些运算指标。`);
  hideIndicatorFormError(); indicatorState.items = indicatorState.items.filter((item) => item.id !== id); if (indicatorState.selectedDetailId === id) indicatorState.selectedDetailId = null; persistWorkspace(); refreshWorkspacePanels();
}
function renderSavedIndicators() {
  $("indicatorCount").textContent = String(indicatorState.items.length); syncDerivedOperandOptions(); for (const id of indicatorState.bulkSelection) if (!itemById(id)) indicatorState.bulkSelection.delete(id); renderBulkBar();
  if (!indicatorState.items.length) { $("savedIndicators").innerHTML = '<p class="empty-list-copy">尚未添加指标。</p>'; return; }
  const bulkTargets = indicatorState.bulkMode ? bulkTargetIds() : new Set();
  const laneOptions = (selected) => indicatorState.chartOrder.map((lane) => `<option value="${lane}" ${String(lane) === String(selected) ? "selected" : ""}>${escapeHtml(chartDisplayName(lane))}</option>`).join("");
  $("savedIndicators").innerHTML = indicatorState.items.map((item) => {
    const label = escapeHtml(indicatorLabel(item)); const picked = bulkTargets.has(item.id); const locked = picked && !indicatorState.bulkSelection.has(item.id);
    const bulkBox = indicatorState.bulkMode ? `<label class="bulk-select ${locked ? "is-locked" : ""}" title="${locked ? "由选中的运算指标带入，取消它即可解除" : "选中以参与批量操作"}"><input type="checkbox" data-bulk-select="${item.id}" ${picked ? "checked" : ""} ${locked ? "disabled" : ""} aria-label="批量选择 ${label}"/></label>` : "";
    return `<article class="saved-indicator ${item.active ? "is-active" : ""} ${item.id === indicatorState.editingId ? "is-editing" : ""} ${indicatorState.bulkMode ? "is-bulk" : ""} ${picked ? "is-bulk-picked" : ""}">${bulkBox}<label class="indicator-toggle"><input type="checkbox" data-indicator-toggle="${item.id}" ${item.active ? "checked" : ""}/><span aria-hidden="true"></span></label><div class="saved-indicator-copy"><strong>${label}</strong><small>${escapeHtml(indicatorDetail(item))}</small><em class="indicator-status status-${item.status}">${escapeHtml(indicatorStatus(item))}</em>${item.error ? `<p>${escapeHtml(item.error)}</p>` : ""}</div><div class="saved-indicator-actions"><select class="indicator-lane-select" data-indicator-lane="${item.id}" aria-label="${label} 所属坐标">${laneOptions(item.config.chartLane)}</select><div class="saved-indicator-buttons"><button class="card-action" type="button" data-indicator-edit="${item.id}">编辑</button><button class="card-action" type="button" data-indicator-duplicate="${item.id}">复制</button><button class="card-action" type="button" data-indicator-detail="${item.id}" ${item.response ? "" : "disabled"}>详情</button></div><button class="delete-indicator" type="button" data-indicator-delete="${item.id}">×</button></div></article>`;
  }).join("");
}
function syncDerivedOperandOptions() { if (indicatorState.draft.type !== "derived") return; const signature = indicatorState.items.map((item) => `${item.id}:${indicatorLabel(item)}`).join("|"); if (signature === indicatorState.operandSignature) return; indicatorState.operandSignature = signature; renderIndicatorConfig(); }

function indicatorAlias(item) { return (item?.config?.alias || "").trim(); }
function indicatorLabel(item, depth = 0) { return indicatorAlias(item) || indicatorTechnicalLabel(item, depth); }
function indicatorTechnicalLabel(item, depth = 0) {
  const config = item.config; if (item.type === "derived") { if (depth > MAX_CHARTS * 2) return "指标运算"; const left = itemById(config.operandA); const right = itemById(config.operandB); return `(${left ? indicatorLabel(left, depth + 1) : "已删除"}) ${OPERATOR_SYMBOLS[config.operator] || "?"} (${right ? indicatorLabel(right, depth + 1) : "已删除"})`; }
  const prefix = `${config.instrumentCode} · `; if (item.type === "implied_vol") return `${prefix}IV · ${coordinateLabel(config)}`; if (item.type === "realized_vol") return `${prefix}RV · ${config.rvWindow} sessions · ${config.rvAlignment}`; if (item.type === "forward") return `${prefix}Forward · ${maturityLabel(config)}`; return `${prefix}Spot · 原始未复权`;
}
function coordinateLabel(config) { const strike = config.strikeKind === "percentage" ? `${config.moneynessBasis === "relative_to_forward" ? "K/F" : "K/S"} ${config.moneyness}%` : config.strikeKind === "delta" ? `Delta ${config.delta}` : `Strike ${config.absoluteStrike}`; return `${maturityLabel(config)} · ${strike}`; }
function maturityLabel(config) { return config.maturityMode === "sliding" ? config.slidingMaturity : `${config.maturityMode} ${config.expiry}`; }
function indicatorDetail(item) { const wire = "bsVol · matrix"; const placement = chartDisplayName(Number(item.config.chartLane)); if (item.type === "derived") return `${placement} · 浏览器本地按共同观察日计算 · 不发送新的取数请求`; if (item.type === "realized_vol") return `${placement} · price-return RV · spot via reference 3M K/F 100% · ${wire} carrier`; if (item.type === "spot") return `${placement} · 数据源 spot · 未复权 · reference 3M K/F 100% · ${wire} carrier`; if (item.type === "forward") return `${placement} · 数据源 forward curve · K/F 100% response carrier · ${wire}`; return `${placement} · ${wire} · exact coordinate · no substitution`; }
function indicatorStatus(item) { if (item.type === "derived" && item.status === "ready") return "已计算"; const label = { queued: "等待加载", loading: "加载中", ready: "已加载", stale: "范围已变化，待刷新", error: "加载失败" }[item.status] || item.status; return isNeededButHidden(item) ? `${label} · 供运算指标使用` : label; }
function indicatorUnit(item, depth = 0) { if (item.type !== "derived") return VOL_TYPES.has(item.type) ? "vol" : PRICE_TYPES.has(item.type) ? "price" : "mixed"; if (depth > MAX_CHARTS * 2) return "mixed"; if (["multiply", "divide"].includes(item.config.operator)) return "ratio"; const left = itemById(item.config.operandA); const right = itemById(item.config.operandB); if (!left || !right) return "mixed"; const unit = indicatorUnit(left, depth + 1); return unit === indicatorUnit(right, depth + 1) ? unit : "mixed"; }
function unitSuffix(item) { return indicatorUnit(item) === "vol" ? "%" : ""; }
function itemColor(item) { return PALETTE[(item.id - 1) % PALETTE.length]; }
function indicatorValueKey(type) { return { implied_vol: "impliedVol", realized_vol: "realizedVol", spot: "spot", forward: "forward" }[type]; }

function addChartLane() { if (indicatorState.chartCount >= MAX_CHARTS) return; indicatorState.chartCount += 1; indicatorState.chartOrder.push(indicatorState.chartCount); indicatorState.chartNames.push(""); indicatorState.draft.chartLane = String(indicatorState.chartCount); persistWorkspace(); renderScopeFields(); refreshWorkspacePanels({ details: false }); }
function handleChartStackClick(event) {
  const button = event.target.closest("[data-chart-remove]"); if (!button) return; const lane = Number(button.dataset.chartRemove);
  if (!Number.isInteger(lane) || lane < 1 || lane > indicatorState.chartCount || indicatorState.chartCount <= 1) return;
  if (indicatorState.items.some((item) => Number(item.config.chartLane) === lane)) return showIndicatorFormError(`${chartDisplayName(lane)} 仍有 indicator；请先在保存卡片中移动或删除这些 indicator。`);
  for (const item of indicatorState.items) if (Number(item.config.chartLane) > lane) item.config.chartLane = String(Number(item.config.chartLane) - 1);
  indicatorState.chartOrder = indicatorState.chartOrder.filter((value) => value !== lane).map((value) => value > lane ? value - 1 : value); indicatorState.chartNames.splice(lane - 1, 1); indicatorState.chartCount -= 1;
  const draftLane = Number(indicatorState.draft.chartLane); if (draftLane > lane) indicatorState.draft.chartLane = String(draftLane - 1); else if (draftLane === lane) indicatorState.draft.chartLane = String(Math.min(lane, indicatorState.chartCount));
  persistWorkspace(); renderScopeFields(); refreshWorkspacePanels({ details: false });
}
function handleChartNameDoubleClick(event) { const host = event.target.closest("[data-chart-name]"); if (host) startChartNameEdit(host); }
function startChartNameEdit(host) {
  const lane = Number(host.dataset.chartName); if (!Number.isInteger(lane) || host.querySelector("input")) return; const input = document.createElement("input"); input.className = "chart-name-input"; input.value = chartDisplayName(lane); input.maxLength = 40; host.textContent = ""; host.appendChild(input); input.focus(); input.select();
  const commit = (save) => { input.removeEventListener("blur", onBlur); if (save) { const value = input.value.trim().slice(0, 40); indicatorState.chartNames[lane - 1] = value && value !== `坐标 ${lane}` ? value : ""; persistWorkspace(); renderScopeFields(); } refreshWorkspacePanels({ details: false }); };
  const onBlur = () => commit(true); input.addEventListener("keydown", (event) => { event.stopPropagation(); if (event.key === "Enter") { event.preventDefault(); commit(true); } else if (event.key === "Escape") { event.preventDefault(); commit(false); } }); input.addEventListener("blur", onBlur);
}
function handleChartDragStart(event) { const handle = event.target.closest("[data-chart-drag]"); if (!handle) return; const lane = Number(handle.dataset.chartDrag); if (!Number.isInteger(lane)) return; indicatorState.chartDragSource = lane; event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", String(lane)); handle.closest("[data-chart-lane]")?.classList.add("is-dragging"); }
function handleChartDragOver(event) { if (indicatorState.chartDragSource === null) return; const panel = event.target.closest("[data-chart-lane]"); if (!panel) return; const target = Number(panel.dataset.chartLane); if (!Number.isInteger(target) || target === indicatorState.chartDragSource) return; event.preventDefault(); event.dataTransfer.dropEffect = "move"; document.querySelectorAll("#indicatorCharts .is-drop-target").forEach((element) => element.classList.remove("is-drop-target")); panel.classList.add("is-drop-target"); }
function handleChartDrop(event) { if (indicatorState.chartDragSource === null) return; const panel = event.target.closest("[data-chart-lane]"); if (!panel) return; const target = Number(panel.dataset.chartLane); const source = indicatorState.chartDragSource; event.preventDefault(); clearChartDragState(); if (!Number.isInteger(target) || source === target) return; const from = indicatorState.chartOrder.indexOf(source); const to = indicatorState.chartOrder.indexOf(target); if (from < 0 || to < 0) return; moveWithin(indicatorState.chartOrder, from, to); persistWorkspace(); renderScopeFields(); refreshWorkspacePanels({ details: false }); }
function clearChartDragState() { indicatorState.chartDragSource = null; document.querySelectorAll("#indicatorCharts .is-dragging, #indicatorCharts .is-drop-target").forEach((element) => element.classList.remove("is-dragging", "is-drop-target")); }

function renderChartShells() {
  const container = $("indicatorCharts"); const signature = `${indicatorState.chartOrder.join(",")}|${indicatorState.chartNames.join("\u001f")}`; if (container.dataset.chartSignature === signature) return;
  chartDivs().forEach((div) => Plotly.purge(div)); container.dataset.chartSignature = signature;
  container.innerHTML = indicatorState.chartOrder.map((lane) => { const remove = indicatorState.chartCount > 1 ? `<button class="remove-chart-button" type="button" data-chart-remove="${lane}">删除坐标</button>` : ""; return `<article class="panel chart-panel timeseries-panel" data-chart-lane="${lane}"><div class="panel-heading"><div class="chart-pane-heading"><span class="chart-drag-handle" draggable="true" data-chart-drag="${lane}" title="拖动调整坐标上下顺序">⠿</span><div><p class="eyebrow">CHART ${lane}</p><h3 data-chart-name="${lane}" title="双击改坐标名称">${escapeHtml(chartDisplayName(lane))}</h3></div></div><div class="chart-pane-actions"><span id="chartPaneCount-${lane}" class="chart-pane-count">0 active</span><span class="axis-note">左轴：波动率 % · 右轴：价格与比值 · 框选缩放</span>${remove}</div></div><div id="indicatorChart-${lane}" class="chart timeseries-chart"></div></article>`; }).join("");
}
function indicatorTrace(item) {
  const points = indicatorState.seriesIndex.get(item.id).points; const flagsByDate = new Map((item.response?.series || []).map((point) => [point.date, point.qualityFlags.join(", ")]));
  return { type: "scatter", mode: "lines", x: points.map((point) => point.date), y: points.map((point) => point.value), name: indicatorLabel(item),
    text: points.map((point) => flagsByDate.get(point.date) || (item.type === "derived" ? "derived" : "")), hovertemplate: "%{x}<br>%{y:.4f}<br>%{text}<extra>%{fullData.name}</extra>",
    line: { color: itemColor(item), width: 2, dash: item.type === "derived" ? "dot" : "solid" }, yaxis: indicatorUnit(item) === "vol" ? "y" : "y2", connectgaps: false };
}
function renderIndicatorChart() {
  if (!window.Plotly || !$("indicatorCharts")) return; renderChartShells(); const active = indicatorState.items.filter((item) => item.active); const ready = active.filter((item) => indicatorState.seriesIndex.get(item.id)?.points); const start = $("startDate").value; const end = $("endDate").value;
  for (const lane of indicatorState.chartOrder) {
    const laneActive = active.filter((item) => Number(item.config.chartLane) === lane); const laneReady = ready.filter((item) => Number(item.config.chartLane) === lane); const traces = laneReady.map(indicatorTrace);
    const annotations = traces.length ? [] : [{ text: laneActive.some((item) => item.status === "loading") ? "正在加载此坐标的 indicator…" : "把 indicator 分配到此坐标", showarrow: false, xref: "paper", yref: "paper", x: 0.5, y: 0.5, font: { color: "#7b8780", size: 14 } }];
    const div = $(`indicatorChart-${lane}`); $(`chartPaneCount-${lane}`).textContent = `${laneActive.length} active · ${laneReady.length} loaded`;
    Promise.resolve(Plotly.react(div, traces, { margin: { l: 62, r: 68, t: 22, b: 48 }, paper_bgcolor: "#fffef9", plot_bgcolor: "#fffef9", hovermode: "x unified", hoverlabel: { bgcolor: "rgba(255,254,249,0.78)", bordercolor: "rgba(126,145,134,0.55)", font: { color: "#334139" } }, dragmode: "zoom", legend: { orientation: "h", y: 1.1, x: 0 }, font: { family: "Inter, Microsoft YaHei, sans-serif", size: 10, color: "#536159" }, xaxis: { title: "Observation date", type: "date", range: start && end ? [start, end] : undefined, gridcolor: "#e8ebe4", showspikes: true, spikemode: "across", spikesnap: "data", spikedash: "dot", spikecolor: "#6f7f76", spikethickness: 1 }, yaxis: { title: "Volatility (%)", gridcolor: "#e8ebe4", zeroline: false }, yaxis2: { title: "Price / ratio", overlaying: "y", side: "right", showgrid: false, zeroline: false }, annotations, uirevision: `chart-${lane}-${start}-${end}` }, { responsive: true, displaylogo: false, modeBarButtonsToRemove: ["lasso2d", "select2d"] })).then(() => bindChartSync(div));
  }
  const instruments = new Set(indicatorState.items.filter((item) => item.type !== "derived").map((item) => item.config.instrumentCode)); $("timeseriesStatus").textContent = `${indicatorState.chartCount}/${MAX_CHARTS} charts · ${active.length} active`; $("timeseriesTitle").textContent = indicatorState.items.length ? `${instruments.size} instruments · ${indicatorState.items.length} indicators` : "空白时序图"; $("timeseriesSubtitle").textContent = `${start || "—"} → ${end || "—"}`; $("addChartButton").disabled = indicatorState.chartCount >= MAX_CHARTS; renderIndicatorWarnings(active);
}
function chartDivs() { return Array.from(document.querySelectorAll("#indicatorCharts .timeseries-chart")); }
function bindChartSync(div) {
  if (!div?.on || div.dataset.syncBound === "true") return; div.dataset.syncBound = "true";
  div.on("plotly_hover", (event) => { if (indicatorState.hoverSyncing) return; const x = event.points?.[0]?.x; syncHover(div, x); renderCrosshairReadout(hoverDateKey(x)); });
  div.on("plotly_unhover", () => { if (!indicatorState.hoverSyncing) clearSynchronizedHover(div); }); div.on("plotly_relayout", (event) => syncXZoom(div, event));
}
function hoverDateKey(value) { return value === undefined || value === null ? null : String(value).slice(0, 10); }
function renderCrosshairReadout(date) {
  const box = $("crosshairReadout"); if (!box) return; indicatorState.hoverDate = date; const active = indicatorState.items.filter((item) => item.active);
  if (!date || !active.length) { box.classList.add("is-hidden"); box.innerHTML = ""; return; }
  const lanes = [];
  for (const lane of indicatorState.chartOrder) { const rows = active.filter((item) => Number(item.config.chartLane) === lane).map((item) => { const value = indicatorState.seriesIndex.get(item.id)?.byDate?.get(date); const text = value === undefined || value === null ? "—" : `${formatNumber(value, 4)}${unitSuffix(item)}`; return `<li><i style="background:${itemColor(item)}"></i><span>${escapeHtml(indicatorLabel(item))}</span><strong class="readout-value${value === undefined || value === null ? " is-missing" : ""}">${escapeHtml(text)}</strong></li>`; }); if (rows.length) lanes.push(`<div class="readout-lane"><small>${escapeHtml(chartDisplayName(lane))}</small><ul>${rows.join("")}</ul></div>`); }
  if (!lanes.length) { box.classList.add("is-hidden"); box.innerHTML = ""; return; } box.classList.remove("is-hidden"); box.innerHTML = `<div class="readout-date"><small>HOVER DATE</small><strong>${escapeHtml(date)}</strong></div><div class="readout-lanes">${lanes.join("")}</div>`;
}
function axisTimestamp(value) { if (value === undefined || value === null) return null; if (typeof value === "number") return value; const parsed = Date.parse(value instanceof Date ? value.toISOString() : String(value)); return Number.isFinite(parsed) ? parsed : null; }
function laneSubplot(div) { return div.data.some((trace) => (trace.yaxis || "y") === "y") ? "xy" : "xy2"; }
function syncHover(source, xValue) { const xval = axisTimestamp(xValue); if (xval === null) return; indicatorState.hoverSyncing = true; try { for (const div of chartDivs()) if (div !== source && Array.isArray(div.data) && div.data.length) Plotly.Fx.hover(div, { xval }, laneSubplot(div)); } finally { indicatorState.hoverSyncing = false; } }
function clearSynchronizedHover(source) { indicatorState.hoverSyncing = true; try { for (const div of chartDivs()) if (div !== source) Plotly.Fx.unhover(div); } finally { indicatorState.hoverSyncing = false; } }
function syncXZoom(source, event) { if (indicatorState.zoomSyncing) return; const update = {}; if (event["xaxis.range[0]"] !== undefined && event["xaxis.range[1]"] !== undefined) { update["xaxis.range[0]"] = event["xaxis.range[0]"]; update["xaxis.range[1]"] = event["xaxis.range[1]"]; } else if (event["xaxis.autorange"] === true) update["xaxis.autorange"] = true; else return; indicatorState.zoomSyncing = true; Promise.all(chartDivs().filter((div) => div !== source).map((div) => Plotly.relayout(div, update))).finally(() => { indicatorState.zoomSyncing = false; }); }

function coordinateRequestLabel(request) { if (request.strike_rule === "fixed") return `${request.maturity_rule} ${request.low_fixed_maturity} · strike ${request.low_fixed_strike}`; if (request.strike_rule === "delta") return `${request.low_maturity} · delta ${request.low_delta_strike}`; const basis = request.strike_rule === "relative_to_forward" ? "K/F" : "K/S"; const maturity = request.low_maturity || `${request.maturity_rule} ${request.low_fixed_maturity}`; return `${maturity} · ${basis} ${request.low_strike}%`; }
async function downloadSelectedCsv() { const item = indicatorState.items.find((candidate) => candidate.id === indicatorState.selectedDetailId && candidate.request); if (!item) return; try { const response = await apiFetch(state.capabilities.endpoints.compareCsv, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(item.request) }); const safe = item.type.replaceAll(/[^a-z0-9_-]/gi, "_"); saveBlob(await response.blob(), `${item.request.volatilityRequest.code}_${safe}_compare.csv`); } catch (error) { showIndicatorFormError(`CSV 生成失败：${error.payload?.message || error.message}`); } }
function renderIndicatorDetails() {
  if (document.querySelector('input[name="queryKind"]:checked')?.value !== "compare") return; const ready = indicatorState.items.filter((item) => item.response && item.status === "ready");
  if (!ready.length) { $("resultWorkspace").classList.add("is-hidden"); $("detailIndicatorField").classList.add("is-hidden"); return; }
  const item = ready.find((candidate) => candidate.id === indicatorState.selectedDetailId) || ready.at(-1); indicatorState.selectedDetailId = item.id;
  $("detailIndicatorSelect").innerHTML = ready.map((candidate) => `<option value="${candidate.id}" ${candidate.id === item.id ? "selected" : ""}>${escapeHtml(indicatorLabel(candidate))}</option>`).join(""); $("detailIndicatorField").classList.remove("is-hidden"); $("resultWorkspace").classList.remove("is-hidden"); $("welcomeState").classList.add("is-hidden"); $("loadingState").classList.add("is-hidden"); $("errorPanel").classList.add("is-hidden"); $("compareCharts").classList.add("is-hidden"); $("surfaceCharts").classList.add("is-hidden");
  renderIndicatorDetailHeader(item); renderIndicatorDetailSummary(item); renderIndicatorDetailTable(item); renderIndicatorDetailMethodology(item); renderIndicatorDetailQuality(item); renderIndicatorDetailActivity(item); renderIndicatorDetailRules(item); renderIndicatorDetailDisclosures(item); renderIndicatorDetailWarnings(item);
}
function renderIndicatorDetailHeader(item) { const request = item.request.volatilityRequest; $("resultEyebrow").textContent = "INDICATOR DETAIL"; $("resultTitle").textContent = indicatorLabel(item); $("resultSubtitle").textContent = `${chartDisplayName(Number(item.config.chartLane))} · ${request.start_date} → ${request.end_date} · 当前只展示所选 indicator 的数据与后台记录`; $("cacheBadge").textContent = item.response.source.cacheStatus.toUpperCase(); $("requestIdBadge").textContent = `Request ${item.response.requestId}`; }
function renderIndicatorDetailSummary(item) { const data = item.response; const key = indicatorValueKey(item.type); const latest = [...data.series].reverse().find((point) => point[key] !== null && point[key] !== undefined); const usable = data.series.filter((point) => point[key] !== null && point[key] !== undefined).length; const value = latest ? latest[key] : null; const suffix = ["implied_vol", "realized_vol"].includes(item.type) ? "%" : ""; const cards = [["Latest selected value", value === null ? "—" : `${formatNumber(value, 3)}${suffix}`, latest?.date || "无有效值"], ["Observations", formatNumber(data.series.length, 0), `${usable} usable selected values`], ["Usable IV", formatNumber(data.dataQuality.usableIvCount, 0), "response coordinate"], ["Invalid IV", formatNumber(data.dataQuality.invalidIvCount, 0), "raw retained · effective null"]]; $("summaryCards").innerHTML = cards.map(([label, valueText, note]) => `<article class="summary-card"><small>${escapeHtml(label)}</small><strong>${escapeHtml(valueText)}</strong><em>${escapeHtml(note)}</em></article>`).join(""); }
function renderIndicatorDetailTable(item) { const key = indicatorValueKey(item.type); const label = TYPE_LABELS[item.type]; const headers = ["Date", `Selected · ${label}`, "Spot · unadjusted", "Forward", "Raw IV %", "Effective IV %", "RV %", "Quality flags"]; $("resultTableHead").innerHTML = `<tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join("")}</tr>`; $("resultTableBody").innerHTML = item.response.series.map((point) => `<tr data-observation-date="${escapeHtml(point.date)}"><td>${escapeHtml(point.date)}</td><td>${tableValue(point[key])}</td><td>${tableValue(point.spot)}</td><td>${tableValue(point.forward)}</td><td>${tableValue(point.rawImpliedVol)}</td><td>${tableValue(point.impliedVol)}</td><td>${tableValue(point.realizedVol)}</td><td>${flagHtml(point.qualityFlags)}</td></tr>`).join(""); $("tableTitle").textContent = `${label} · 完整响应明细`; $("tableCount").textContent = `${item.response.series.length} rows`; $("tableFootnote").textContent = "Selected 列是图中该 indicator 使用的值；其余字段用于审计数据源响应与质量标记。无效 raw IV 保留，但 effective IV 可为空。"; }
function renderRequestAudit(audit) { if (!audit?.upstreamRequests?.length) return '<div class="request-audit-empty">当前响应没有 request audit；重启到新后端版本后可查看实际 Cortex wire body。</div>'; const cards = audit.upstreamRequests.map((entry, index) => { const sent = entry.sentToUpstream; const disposition = String(entry.disposition || "unknown").toUpperCase(); const note = sent ? "本次实际发送给 Cortex DataHub。" : disposition === "FIXTURE" ? "本次使用离线 fixture，没有调用 Cortex。" : "本次没有调用 Cortex；该有效请求由缓存满足。"; return `<article class="request-audit-card ${sent ? "is-live" : "is-cache"}"><div class="request-audit-card-head"><div><small>BNP API REQUEST ${index + 1}</small><strong>POST /v1/implied-volatility</strong></div><span class="request-mode-badge">${escapeHtml(sent ? "LIVE · SENT" : disposition)}</span></div><p>${escapeHtml(note)}</p><details><summary>查看 wire JSON</summary><pre>${escapeHtml(JSON.stringify(entry.body || {}, null, 2))}</pre></details></article>`; }).join(""); return `<div class="request-audit"><div class="request-audit-title"><strong>后台请求审计</strong><span>序列化后的 Cortex body；不包含 token / secret。</span></div><details class="user-request-json"><summary>查看用户显示范围 request JSON</summary><pre>${escapeHtml(JSON.stringify(audit.userRequestBody || {}, null, 2))}</pre></details><div class="request-audit-grid">${cards}</div></div>`; }
function renderIndicatorDetailMethodology(item) { const data = item.response; const request = item.request.volatilityRequest; const audit = data.requestAudit; const upstream = audit?.upstreamRequests || []; const sentCount = upstream.filter((entry) => entry.sentToUpstream).length; const displayRange = `${request.start_date} → ${request.end_date}`; const firstBody = upstream[0]?.body; const fetchRange = firstBody?.startDate && firstBody?.endDate ? `${firstBody.startDate} → ${firstBody.endDate}` : displayRange; $("methodologyContent").innerHTML = `${definitionGrid([["Selected indicator", indicatorLabel(item)], ["Requested coordinate", coordinateRequestLabel(request)], ["Display range", displayRange], ["Effective fetch range", fetchRange], ["Source mode", String(data.source.cacheStatus || "unknown").toUpperCase()], ["Data status", data.source.isStale ? "STALE — latest refresh failed" : "FRESH / locally confirmed"], ["Actual upstream calls", String(sentCount)], ["Provider", `${data.source.provider} · API ${data.source.apiVersion}`], ["Oldest contributing fetch", data.source.oldestRetrievedAt || data.source.retrievedAt], ["Newest contributing fetch", data.source.newestRetrievedAt || data.source.retrievedAt], ["Refresh attempted", data.source.refreshAttemptedAt || "—"], ["Refresh failure", data.source.staleReason || "—"], ["Request ID", data.requestId]])}${fetchRange !== displayRange ? '<p class="request-range-note">后台为 RV warm-up / forward-tail 覆盖扩大了取数日期；展示日期范围没有改变。</p>' : ""}${renderRequestAudit(audit)}`; }
function deriveIssuesFromSeries(item) { const request = item.request.volatilityRequest; return (item.response.series || []).flatMap((point) => (point.qualityFlags || []).filter((code) => code !== "OK").map((code) => ({ severity: ["INSUFFICIENT_HISTORY", "DUPLICATE_IDENTICAL_REMOVED", "SOURCE_ORDER_CORRECTED"].includes(code) ? "info" : "warning", code, instrumentCode: request.code, date: point.date, coordinate: coordinateRequestLabel(request), rawImpliedVol: point.rawImpliedVol, impliedVol: point.impliedVol, realizedVol: point.realizedVol, spot: point.spot, forward: point.forward, action: "请在 Observation table 查看该日期完整字段。" }))); }
function issueCardHtml(issue) { const values = []; const code = String(issue.code || ""); if (code.includes("IV")) { values.push(["Raw IV", issue.rawImpliedVol == null ? "—" : `${issue.rawImpliedVol}%`]); values.push(["Effective IV", issue.impliedVol == null ? "—" : `${issue.impliedVol}%`]); } if (["RETURN_OUTLIER", "MISSING_SPOT"].includes(code)) values.push(["Spot", issue.spot ?? "—"]); if (code === "MISSING_FORWARD") values.push(["Forward", issue.forward ?? "—"]); if (code === "INSUFFICIENT_HISTORY") values.push(["RV", issue.realizedVol == null ? "—" : `${issue.realizedVol}%`]); return `<article class="quality-issue ${issue.severity === "info" ? "is-info" : "is-warning"}"><div class="quality-issue-head"><span>${escapeHtml(issue.severity === "info" ? "INFO" : "WARNING")}</span><strong>${escapeHtml(code)}</strong></div><div class="quality-issue-meta"><b>${escapeHtml(issue.instrumentCode || "—")}</b><b>${escapeHtml(issue.date || "—")}</b><span>${escapeHtml(issue.coordinate || "—")}</span></div>${values.length ? `<div class="quality-issue-values">${values.map(([label, value]) => `<span><small>${escapeHtml(label)}</small><strong>${escapeHtml(String(value))}</strong></span>`).join("")}</div>` : ""}<p>${escapeHtml(issue.action || "保留质量标记，建议复核。")}</p><button class="text-button issue-locate-button" type="button" data-issue-date="${escapeHtml(issue.date || "")}">定位到 Observation</button></article>`; }
function renderIndicatorDetailQuality(item) { const q = item.response.dataQuality; const issues = Array.isArray(item.response.issues) ? item.response.issues : deriveIssuesFromSeries(item); const warn = issues.filter((issue) => issue.severity !== "info").length; const info = issues.length - warn; $("qualityStatus").textContent = issues.length ? `${warn} WARN · ${info} INFO` : "OK"; $("qualityStatus").classList.toggle("is-warning", issues.length > 0); const counts = `<div class="quality-counts">${[["Observations", q.observationCount], ["Usable IV", q.usableIvCount], ["Invalid IV", q.invalidIvCount]].map(([label, value]) => `<div class="quality-count"><small>${escapeHtml(label)}</small><strong>${formatNumber(value, 0)}</strong></div>`).join("")}</div>`; $("qualityContent").innerHTML = !issues.length ? `${counts}<div class="quality-ok-state"><strong>✓ No data-quality issues detected</strong><span>${formatNumber(q.observationCount, 0)} displayed observations · no flags</span></div>` : `${counts}<div class="quality-issue-summary"><strong>${issues.length} 项需要查看</strong><span>这里只列本次请求实际触发的 flag。通用处理规则在「方法与数据规则」。</span></div><div class="quality-issue-list">${issues.map(issueCardHtml).join("")}</div>`; }
function handleQualityIssueClick(event) { const button = event.target.closest("[data-issue-date]"); if (!button) return; const row = Array.from(document.querySelectorAll("#resultTableBody tr")).find((candidate) => candidate.dataset.observationDate === button.dataset.issueDate); if (!row) return; row.scrollIntoView({ behavior: "smooth", block: "center" }); row.classList.add("is-quality-focus"); window.setTimeout(() => row.classList.remove("is-quality-focus"), 1800); }
function renderIndicatorDetailActivity(item) { const events = item.response.activity || []; const normal = new Set(["REQUEST_VALIDATED", "FIXTURE_LOADED", "CACHE_HIT", "UPSTREAM_FETCH_STARTED", "UPSTREAM_FETCH_COMPLETED", "SCHEMA_VALIDATED", "COORDINATES_RESOLVED", "ANALYTICS_COMPLETED", "BROWSER_RENDER_READY"]); const noteworthy = events.filter((event) => !normal.has(event.code)); if ($("activityDetails")) $("activityDetails").open = noteworthy.length > 0; if ($("activityDetailsSummary")) $("activityDetailsSummary").textContent = noteworthy.length ? `执行记录 · ${noteworthy.length} 项需关注` : `执行记录 · ${events.length} steps · 正常`; $("activityList").innerHTML = events.map((event) => `<li class="${normal.has(event.code) ? "" : "is-noteworthy"}"><span class="activity-stage">${escapeHtml(event.stage)}</span><div class="activity-message"><strong>${escapeHtml(event.code)}${event.affectedObservations ? ` · ${formatNumber(event.affectedObservations, 0)}` : ""}</strong><p>${escapeHtml(event.message)}</p>${event.suggestedAction ? `<p class="activity-action">建议：${escapeHtml(event.suggestedAction)}</p>` : ""}</div></li>`).join(""); }
function renderIndicatorDetailRules(item) { const method = item.response.methodology; if ($("methodologyRulesContent")) $("methodologyRulesContent").innerHTML = definitionGrid([["IV definition", method.ivLabel], ["RV definition", method.rvLabel], ["RV formula", method.rvFormula], ["RV window", `${method.rvWindowSessions} trading sessions · ${method.rvAlignment}`], ["Annualization", `${method.annualization} trading sessions`], ["Spot / RV source", method.spotNote], ["Corporate action adjustment", method.corporateActionAdjustment]]); }
function renderIndicatorDetailDisclosures(item) { for (const id of ["methodologyDisclosures", "qualityDisclosures", "activityDisclosures"]) if ($(id)) $(id).innerHTML = ""; const host = $("methodologyRulesDisclosures"); if (!host) return; const context = new Set(["compare", "implied_vol", "source_metadata", "upstream_fetch", "cache", "csv", "health", "request_builder", item.type]); const entries = (item.response.disclosures || []).filter((entry) => !Array.isArray(entry.appliesTo) || !entry.appliesTo.length || entry.appliesTo.some((token) => context.has(token))); host.innerHTML = entries.map((entry) => `<details class="rule-entry"><summary><span>${escapeHtml(entry.title)}</span><small>${escapeHtml(entry.category || "rule")}</small></summary><p>${escapeHtml(entry.summary || "")}</p>${entry.details?.length ? `<ul>${entry.details.map((detail) => `<li>${escapeHtml(detail)}</li>`).join("")}</ul>` : ""}</details>`).join(""); }
function renderIndicatorDetailWarnings(item) { const messages = []; if (item.response.dataQuality.warningBanner) messages.push(item.response.dataQuality.warningBanner); item.response.activity.filter((event) => ["FORWARD_RV_INCOMPLETE", "LARGE_SURFACE_RESULT"].includes(event.code)).forEach((event) => messages.push(event.message)); $("warningBanner").classList.toggle("is-hidden", messages.length === 0); $("warningBanner").innerHTML = messages.map((message) => `<strong>WARNING</strong> · ${escapeHtml(message)}`).join("<br>"); const missing = item.response.series.filter((point) => point.qualityFlags.some((flag) => ["MISSING_IV", "MATURITY_MISMATCH", "STRIKE_MISMATCH"].includes(flag))); $("coordinateHint").classList.toggle("is-hidden", missing.length === 0); $("coordinateHint").innerHTML = missing.length ? `<strong>精确坐标缺失：</strong>${missing.length} 个日期没有请求坐标的数据；系统没有使用邻近值。` : ""; }

function bindStatsColumnControls() {
  $("statsColumnList").addEventListener("change", (event) => { const toggle = event.target.closest("[data-column-toggle]"); if (!toggle) return; const entry = indicatorState.statsColumns.find((column) => column.id === toggle.dataset.columnToggle); if (!entry) return; entry.visible = toggle.checked; persistStatsColumns(); renderStatsColumnConfig(); renderIndicatorStats(); });
  $("statsColumnList").addEventListener("click", (event) => { const move = event.target.closest("[data-column-move]"); if (!move) return; const index = indicatorState.statsColumns.findIndex((column) => column.id === move.dataset.columnId); const target = move.dataset.columnMove === "up" ? index - 1 : index + 1; if (index < 0 || target < 0 || target >= indicatorState.statsColumns.length) return; [indicatorState.statsColumns[index], indicatorState.statsColumns[target]] = [indicatorState.statsColumns[target], indicatorState.statsColumns[index]]; persistStatsColumns(); renderStatsColumnConfig(); renderIndicatorStats(); });
  $("statsColumnsResetButton").addEventListener("click", () => { indicatorState.statsColumns = STAT_COLUMNS.map((column) => ({ id: column.id, visible: column.defaultVisible !== false })); persistStatsColumns(); renderStatsColumnConfig(); renderIndicatorStats(); });
  $("statsWidthResetButton").addEventListener("click", () => { indicatorState.columnWidths = {}; persistWorkspace(); renderIndicatorStats(); }); $("indicatorStatsHead").addEventListener("pointerdown", startColumnResize); bindStatsDragControls();
}
function renderStatsColumnConfig() { const list = $("statsColumnList"); if (!list) return; const known = new Map(STAT_COLUMNS.map((column) => [column.id, column])); list.innerHTML = indicatorState.statsColumns.map((entry, index) => { const column = known.get(entry.id); return `<div class="stats-column-row"><label><input type="checkbox" data-column-toggle="${entry.id}" ${entry.visible ? "checked" : ""} /><span>${escapeHtml(column.label)}</span></label><span class="stats-column-move"><button type="button" data-column-move="up" data-column-id="${entry.id}" ${index === 0 ? "disabled" : ""}>↑</button><button type="button" data-column-move="down" data-column-id="${entry.id}" ${index === indicatorState.statsColumns.length - 1 ? "disabled" : ""}>↓</button></span></div>`; }).join(""); $("statsColumnSummary").textContent = `统计项设置 · ${indicatorState.statsColumns.filter((entry) => entry.visible).length}/${indicatorState.statsColumns.length}`; }
function indicatorAlias(item) { return (item?.config?.alias || "").trim(); }
function setIndicatorAlias(item, value) { if (!item) return; const trimmed = value.trim().slice(0, 60); item.config.alias = trimmed && trimmed !== indicatorTechnicalLabel(item) ? trimmed : ""; persistWorkspace(); }
function startIndicatorAliasEdit(host) { const item = itemById(host.dataset.indicatorAlias); if (!item || host.querySelector("input")) return; const input = document.createElement("input"); input.className = "stats-alias-input"; input.value = indicatorLabel(item); host.textContent = ""; host.draggable = false; host.appendChild(input); input.focus(); input.select(); const commit = (save) => { input.removeEventListener("blur", onBlur); if (save) setIndicatorAlias(item, input.value); refreshWorkspacePanels({ details: false }); }; const onBlur = () => commit(true); input.addEventListener("keydown", (event) => { event.stopPropagation(); if (event.key === "Enter") { event.preventDefault(); commit(true); } else if (event.key === "Escape") { event.preventDefault(); commit(false); } }); input.addEventListener("blur", onBlur); }
function bindStatsDragControls() { const table = $("indicatorStatsTable"); table.addEventListener("dragstart", (event) => { const cell = event.target.closest("[data-drag-handle]")?.closest("[data-drag-column], [data-drag-row]"); if (!cell || document.body.classList.contains("is-resizing-column")) return; indicatorState.dragSource = cell.dataset.dragColumn ? { kind: "column", key: cell.dataset.dragColumn } : { kind: "row", key: cell.dataset.dragRow }; event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", indicatorState.dragSource.key); cell.classList.add("is-dragging"); }); table.addEventListener("dragover", (event) => { const target = statsDropTarget(event); if (!target) return; event.preventDefault(); event.dataTransfer.dropEffect = "move"; table.querySelectorAll(".is-drop-target").forEach((element) => element.classList.remove("is-drop-target")); target.cell.classList.add("is-drop-target"); }); table.addEventListener("drop", (event) => { const target = statsDropTarget(event); if (!target) return; event.preventDefault(); applyStatsReorder(target.key); }); table.addEventListener("dragend", clearStatsDragState); table.addEventListener("dblclick", (event) => { const host = event.target.closest("[data-indicator-alias]"); if (host) startIndicatorAliasEdit(host); }); }
function statsDropTarget(event) { const source = indicatorState.dragSource; if (!source) return null; const cell = event.target.closest(source.kind === "column" ? "[data-drag-column]" : "[data-drag-row]"); if (!cell) return null; const key = source.kind === "column" ? cell.dataset.dragColumn : cell.dataset.dragRow; return key === source.key ? null : { cell, key }; }
function applyStatsReorder(targetKey) { const source = indicatorState.dragSource; clearStatsDragState(); if (!source) return; if (source.kind === "column") { const from = indicatorState.items.findIndex((item) => String(item.id) === source.key); const to = indicatorState.items.findIndex((item) => String(item.id) === targetKey); if (from < 0 || to < 0) return; moveWithin(indicatorState.items, from, to); persistWorkspace(); refreshWorkspacePanels({ details: false }); return; } const from = indicatorState.statsColumns.findIndex((column) => column.id === source.key); const to = indicatorState.statsColumns.findIndex((column) => column.id === targetKey); if (from < 0 || to < 0) return; moveWithin(indicatorState.statsColumns, from, to); persistStatsColumns(); renderStatsColumnConfig(); renderIndicatorStats(); }
function clearStatsDragState() { indicatorState.dragSource = null; $("indicatorStatsTable").querySelectorAll(".is-dragging, .is-drop-target").forEach((element) => element.classList.remove("is-dragging", "is-drop-target")); }
function startColumnResize(event) { const handle = event.target.closest("[data-resize-key]"); if (!handle) return; event.preventDefault(); const key = handle.dataset.resizeKey; const column = document.querySelector(`#indicatorStatsCols col[data-column-key="${CSS.escape(key)}"]`); const header = handle.closest("th"); if (!column || !header) return; const startX = event.clientX; const startWidth = header.getBoundingClientRect().width; handle.setPointerCapture(event.pointerId); document.body.classList.add("is-resizing-column"); const was = header.draggable; header.draggable = false; const move = (e) => { const width = Math.max(MIN_COLUMN_WIDTH, Math.round(startWidth + e.clientX - startX)); indicatorState.columnWidths[key] = width; column.style.width = `${width}px`; applyStatsTableWidth(); }; const finish = () => { handle.removeEventListener("pointermove", move); handle.removeEventListener("pointerup", finish); handle.removeEventListener("pointercancel", finish); document.body.classList.remove("is-resizing-column"); header.draggable = was; persistWorkspace(); }; handle.addEventListener("pointermove", move); handle.addEventListener("pointerup", finish); handle.addEventListener("pointercancel", finish); }
function columnWidth(key, fallback) { return indicatorState.columnWidths[key] || fallback; }
function autoSeriesWidth(count, labelWidth) { const container = $("indicatorStatsTable")?.parentElement?.clientWidth || 0; if (!count || !container) return DEFAULT_SERIES_WIDTH; return Math.max(MIN_AUTO_SERIES_WIDTH, Math.floor((container - labelWidth - 2) / count)); }
function applyStatsTableWidth() { const table = $("indicatorStatsTable"); if (!table) return; const total = Array.from(document.querySelectorAll("#indicatorStatsCols col")).reduce((sum, column) => sum + (Number.parseFloat(column.style.width) || 0), 0); table.style.width = total > 0 ? `${total}px` : ""; }
function resizeHandle(key) { return `<span class="column-resizer" data-resize-key="${escapeHtml(key)}" role="separator" aria-label="调整列宽"></span>`; }
function formatFixed(value, digits) { return new Intl.NumberFormat("zh-HK", { minimumFractionDigits: digits, maximumFractionDigits: digits }).format(value); }
function valueDigits(item) { const unit = indicatorUnit(item); return unit === "vol" ? 1 : unit === "price" ? 2 : 3; }
function percentileBucket(value) { return value >= 80 ? "heat-high" : value >= 60 ? "heat-mid-high" : value > 40 ? "heat-mid" : value > 20 ? "heat-mid-low" : "heat-low"; }
function zScoreBucket(value) { return value >= 2 ? "heat-high" : value >= 1 ? "heat-mid-high" : value > -1 ? "heat-mid" : value > -2 ? "heat-mid-low" : "heat-low"; }
function statCell(column, item, stats) { if (!stats) return '<td class="cell-missing">—</td>'; if (column.id === "lane") return `<td>${escapeHtml(chartDisplayName(Number(item.config.chartLane)))}</td>`; const value = stats[column.id]; if (column.kind === "text") return `<td>${escapeHtml(value ?? "—")}</td>`; if (column.kind === "count") return `<td class="stat-number">${escapeHtml(formatNumber(value, 0))}</td>`; if (column.kind === "percentile" || column.kind === "zscore") { if (value == null) return '<td class="cell-missing">—</td>'; const bucket = column.kind === "percentile" ? percentileBucket(value) : zScoreBucket(value); const text = column.kind === "percentile" ? `${formatFixed(value, 1)}%` : formatFixed(value, 2); return `<td class="heat-cell ${bucket}">${escapeHtml(text)}</td>`; } if (value == null) return '<td class="cell-missing">—</td>'; if (column.kind === "percent") return `<td class="stat-number">${escapeHtml(`${formatFixed(value, 1)}%`)}</td>`; if (column.kind === "ratio") return `<td class="stat-number">${escapeHtml(formatFixed(value, 2))}</td>`; const text = `${formatFixed(value, valueDigits(item))}${unitSuffix(item)}`; const sign = column.kind === "signed" && value !== 0 ? (value > 0 ? " stat-up" : " stat-down") : ""; const prefix = column.kind === "signed" && value > 0 ? "+" : ""; return `<td class="stat-number${sign}">${escapeHtml(`${prefix}${text}`)}</td>`; }
function renderIndicatorStats() { const body = $("indicatorStatsBody"); if (!body) return; const rows = visibleStatsColumns(); const active = indicatorState.items.filter((item) => item.active); const series = active.map((item) => { const entry = indicatorState.seriesIndex.get(item.id); return { item, stats: summarizeSeries(entry?.points), error: entry?.error || null }; }); const labelWidth = columnWidth(STATS_LABEL_COLUMN, DEFAULT_LABEL_WIDTH); $("indicatorStatsCols").innerHTML = [`<col data-column-key="${STATS_LABEL_COLUMN}" style="width:${labelWidth}px" />`, ...series.map(({ item }) => `<col data-column-key="${item.id}" style="width:${columnWidth(String(item.id), autoSeriesWidth(series.length, labelWidth))}px" />`)].join(""); applyStatsTableWidth(); $("indicatorStatsHead").innerHTML = `<tr><th class="stats-label-cell">统计项${resizeHandle(STATS_LABEL_COLUMN)}</th>${series.map(({ item, stats, error }) => `<th class="stats-series-head" data-drag-column="${item.id}"><span class="stats-series-name ${indicatorAlias(item) ? "is-aliased" : ""}" draggable="true" data-drag-handle data-indicator-alias="${item.id}" title="${escapeHtml(indicatorAlias(item) ? `原名：${indicatorTechnicalLabel(item)} · 拖动排序 · 双击改别名` : "拖动排序 · 双击改别名")}">${escapeHtml(indicatorLabel(item))}</span>${stats ? "" : `<small class="stats-series-note">${escapeHtml(error || "当前范围内没有有效值")}</small>`}${resizeHandle(String(item.id))}</th>`).join("")}</tr>`; if (!series.length) { body.innerHTML = '<tr><td class="cell-missing">没有启用中的 indicator。</td></tr>'; $("indicatorStatsCount").textContent = "0 series"; return; } body.innerHTML = rows.map((column) => `<tr><th scope="row" class="stats-label-cell" data-drag-row="${escapeHtml(column.id)}"><span class="stats-row-name" draggable="true" data-drag-handle title="拖动可调整统计项顺序">${escapeHtml(column.label)}</span></th>${series.map(({ item, stats }) => statCell(column, item, stats)).join("")}</tr>`).join(""); $("indicatorStatsCount").textContent = `${series.length} series`; }
function renderIndicatorWarnings(active) { const errors = active.filter((item) => item.status === "error"); const stale = active.filter((item) => item.response?.source?.isStale); const invalid = active.filter((item) => item.type === "implied_vol").reduce((count, item) => count + (item.response?.dataQuality?.invalidIvCount || 0), 0); const warning = $("timeseriesWarning"); const messages = []; if (stale.length) messages.push(`STALE DATA — 最新 Cortex 刷新失败，正在显示本地历史数据。最近成功获取：${stale.map((item) => `${indicatorLabel(item)}：${item.response.source.newestRetrievedAt || item.response.source.retrievedAt}`).join("；")}`); if (errors.length) messages.push(`${errors.length} 个激活指标加载失败；查看左侧指标卡的原始错误。`); if (invalid) messages.push(`${invalid} 个非正/无效 IV 点保留 raw value，但图中为空且不连接。`); warning.classList.toggle("is-stale", stale.length > 0); warning.classList.toggle("is-hidden", !messages.length); warning.textContent = messages.join(" "); }

window.volcurveCompareDetails = { downloadSelectedCsv };
